import { test, expect } from '@playwright/test';

test('reset pass test', async ({ page }) => {
    //   await page.goto('chrome-error://chromewebdata/');
    //   await page.getByRole('button', { name: 'Advanced' }).click();
    await page.getByRole('link', { name: 'Proceed to app-rnd01.therapbd' }).click();
    await page.getByRole('link', { name: 'Login' }).click();
    await page.getByRole('link', { name: 'Forgot your password?' }).click();
    await page.getByRole('textbox', { name: 'Enter the email with which' }).click();
    await page.getByRole('textbox', { name: 'Enter the email with which' }).fill('smith04@gmail.com');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByText('No user found with the').click();
    await page.getByRole('textbox', { name: 'Enter the email with which' }).click();
    await page.getByRole('textbox', { name: 'Enter the email with which' }).fill('demo@gmail.com');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByText('No user found with the').click();
    await page.getByRole('textbox', { name: 'Enter the email with which' }).dblclick();
    await page.getByRole('textbox', { name: 'Enter the email with which' }).fill('student1@gmail.com');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByText('Email verified successfully!').click();
    await page.getByRole('textbox', { name: 'Enter a new password' }).click();
    await page.getByRole('textbox', { name: 'Enter a new password' }).fill('as');
    await page.locator('div').filter({ hasText: /^Enter a new password$/ }).locator('svg').click();
    await page.getByRole('textbox', { name: 'Confirm your new password' }).click();
    await page.getByRole('textbox', { name: 'Confirm your new password' }).fill('as');
    await page.locator('div').filter({ hasText: /^Confirm your new password$/ }).locator('svg').click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByText('Password reset failed!').click();
    await page.getByText('Password must be at least 8').click();
    await page.getByRole('textbox', { name: 'Enter a new password' }).click();
    await page.getByRole('textbox', { name: 'Enter a new password' }).click();
    await page.getByRole('textbox', { name: 'Enter a new password' }).fill('Test@123');
    await page.getByRole('textbox', { name: 'Confirm your new password' }).click();
    await page.getByRole('textbox', { name: 'Confirm your new password' }).dblclick();
    await page.getByRole('textbox', { name: 'Confirm your new password' }).fill('Test@123');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByText('User information update').click();
    await page.getByRole('textbox', { name: 'Email Address' }).click();
    await page.getByRole('textbox', { name: 'Email Address' }).fill('student1@gmail.com');
    await page.getByRole('textbox', { name: 'Password' }).click();
    await page.getByRole('textbox', { name: 'Password' }).fill('Test@123');
    await page.getByRole('button', { name: 'Login' }).click();
    await page.getByRole('link', { name: 'Dashboard' }).click();
    await page.getByRole('link', { name: 'Courses' }).click();
    page.once('dialog', dialog => {
        console.log(`Dialog message: ${dialog.message()}`);
        dialog.dismiss().catch(() => { });
    });
    await page.getByRole('link', { name: 'Logout' }).click();
});